### PR TITLE
Fix type issue

### PR DESCRIPTION
**Pull request by natjoe4**
# Summary
Fixing some type issues introduced and uncaught in #62

## New Behavior
Fixed linting and type errors in the unit tests. No new behavior

## Code Changes
Updated unit testing Measure Bundle fixtures to include additional properties created in #62 
Updated MeasureFileUpload components in unit tests to have mocked logError function

# Testing Guidance
- `npm run check`
- Give. an extra look to unit testing files and make sure there are not linting/ts errors

### CODE REVIEW

**Review by elsaperelli — APPROVED** [review]
Thanks for doing this!

**Review by lmd59 — COMMENTED** [review]
Yay! This fixes all of the issues and makes sense for testing updates. Two potential recommendations:

1. Recommend `package.json` update on line 14 to: `"lint": "next lint && tsc --noEmit",`. This appropriately identifies the ts errors in these files during our `npm run check` checks on main, and then appropriately identifies no errors on this branch!
2. (more optional since I'm not sure it's in scope) I don't know if you've also seen this console error come up for the PatientCreationPanel.test.tsx?...
```
PASS  __tests__/components/patient-creation/PatientCreationPanel.test.tsx (11.909 s)
  ● Console

    console.error
      TypeError: textRange(...).getClientRects is not a function
          at textCoords (/Users/laurend/Projects/AbacusFHIR/src/fqm-testify/node_modules/@codemirror/view/dist/index.cjs:769:43)
```
This seems to be a known issue with CodeMirror and jest: https://github.com/jsdom/jsdom/issues/3002 and there's a workaround on this thread that does seem to get rid of the console error for me. Let me know if you think it makes sense to try to fix that problem at this juncture!

**Comment by elsaperelli** [comment]
> 2\. (more optional since I'm not sure it's in scope) I don't know if you've also seen this console error come up for the PatientCreationPanel.test.tsx?...

I think I got this at one point and I did an `npm install` and it seemed to fix it. I don't seem to be getting it anymore.

**Comment by lmd59** [comment]
> > 2. (more optional since I'm not sure it's in scope) I don't know if you've also seen this console error come up for the PatientCreationPanel.test.tsx?...
> 
> I think I got this at one point and I did an `npm install` and it seemed to fix it. I don't seem to be getting it anymore.

It might be intermittent? `npm install' did not seem to fix it for me

**Review by lmd59 — APPROVED** [review]
Approving with package.json update. We'll keep an eye out for the console error, but definitely don't want to hold it up if it's environment specific!

**Pull request merged**
