### PR TITLE
Patient creation

### PR DESCRIPTION
**Pull request by mgramigna**
# Summary

Adds a button/simple code editor for creating a patient resource. Created patients will show up in the app and are editable/deletable

## New Behavior

New button that triggers patient creation where user can edit the FHIR Patient resource content. Currently generates a random name, and DOB that makes them 21 years old w/r/t the start of the measurement period.

## Code Changes

* Add component for generic codemirror modal. Can be re-used for editing any JSON resource, not just patients
* Add patient creation component that handles logic of instantiating a specific test case
* Add helper code for generating random attributes on the resource, as well as the resource itself (uses same fake name/gender data set as Synthea)
* Use Immer to control an immutable state object for all patient test cases across the app

# Testing Guidance

* Test adding a new patient with the button. Make sure that canceling doesn't save changes, that saving does, etc.
* Test editing an already created patient
* Test deletion
* Try to break stuff

### CODE REVIEW

**Review by natjoe4 — CHANGES_REQUESTED** [review]
All functionality works well and looks good. Just left a few smaller comments

**Review by hossenlopp — APPROVED** [review]
Looks like a fantastic start! Only issue is with the editor not warning you when you have invalid JSON. I presume this will come later with validation.

**Review by hossenlopp — APPROVED** [review]
Looks great!

**Review by natjoe4 — APPROVED** [review]
Looks great to me!

**Pull request merged**
